#!/data/data/com.termux/files/usr/bin/bash 
rm /sdcard/info.txt
sleep 0.2
echo '[✓] deleted previpus txt'
PTH='/sdcard/info.txt'
echo 'path is '$PTH
echo '---server.js---' >> /sdcard/info.txt
cat *js >> $PTH
echo '---index.html---' >> /sdcard/info.txt
cat *html >> $PTH
echo '      ✓ DONE'
